# Generated by Django 5.1.3 on 2025-01-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('normal_sprite', models.URLField()),
                ('shiny_sprite', models.URLField()),
                ('egg_moves', models.JSONField(blank=True, default=list)),
                ('moves', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
