# Generated by Django 5.1.3 on 2025-01-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='generation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
