# Generated by Django 5.1.3 on 2025-01-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='final_evolution',
            field=models.BooleanField(default=False),
        ),
    ]
