# Generated by Django 5.1.3 on 2025-01-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_final_evolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolutions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pre_evolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
