# Generated by Django 5.1.3 on 2025-01-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_evolutions_pokemon_pre_evolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolution_chain',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
